### ISSUE TITLE
Problems using `without_id`

### ISSUE THREAD

**Issue by rippinrobr** [spacekookie/barrel#18]
Hi, I'm having an issue using the `without_id` call.  I am trying to generate a create table statement that does not have an id column but I'm either doing something wrong or the without_id call isn't working. I couldn't find an example so I did some searching in the repo and found this comment https://github.com/spacekookie/barrel/blob/f44b4d3c99e4d488685f342b0f910336ca2ff749/examples/pg_strings.rs#L10 so I tried the following:

```
let mut m = Migration::new();
let cols = columns.clone();
m.create_table(name, move |t| {
   //t.meta.without_id();
   for cd in &cols {
     let cname: &str = &cd.name;
     t.add_column(cname, cd.data_type.to_database_type());
   }
}).without_id();
```

If tried it with the `t.meta.without_id()` at the top and bottom instead of after the call without any luck.  Any help would be greatly appreciated.  Thank you for the library!

I am using:
* rustc 1.28.0-nightly (5d0631a64 2018-05-30)
* on a mac
* here's my `cargo.toml` as well.  
* The output of my code is after the cargo.toml file
* Let me know if you need anything else from me.

```
[package]
name = "csv2api"
version = "0.1.0"
authors = ["Rob Rowe <robrowe04@gmail.com>"]

[dependencies]
actix = "0.5"
barrel = "0.2.1"
clap = "2.31.2"
codegen = { git = "https://github.com/carllerche/codegen" } # Soon on crates.io
csv = "1.0.0"
futures = "0.1"
regex = "1.0.0"
# rusqlite = "0.13.0"
sqlite = "0.23.9"
serde_derive = "1.0.66"
serde_json = "1.0.19"
```

```
CREATE TABLE "AwardsManagers" ("id" SERIAL PRIMARY KEY, "playerID" TEXT, "awardID" TEXT, "yearID" INTEGER, "lgID" TEXT, "tie" TEXT, "notes" TEXT);
CREATE TABLE "Managers" ("id" SERIAL PRIMARY KEY, "playerID" TEXT, "yearID" INTEGER, "teamID" TEXT, "lgID" TEXT, "inseason" INTEGER, "G" INTEGER, "W" INTEGER, "L" INTEGER, "rank" TEXT, "plyrMgr" TEXT);
CREATE TABLE "AwardsPlayers" ("id" SERIAL PRIMARY KEY, "playerID" TEXT, "awardID" TEXT, "yearID" INTEGER, "lgID" TEXT, "tie" TEXT, "notes" TEXT);
CREATE TABLE "Fielding" ("id" SERIAL PRIMARY KEY, "playerID" TEXT, "yearID" INTEGER, "stint" INTEGER, "teamID" TEXT, "lgID" TEXT, "POS" TEXT, "G" INTEGER, "GS" TEXT, "InnOuts" TEXT, "PO" INTEGER, "A" INTEGER, "E" TEXT, "DP" INTEGER, "PB" TEXT, "WP" TEXT, "SB" TEXT, "CS" TEXT, "ZR" TEXT);
CREATE TABLE "Salaries" ("id" SERIAL PRIMARY KEY, "yearID" INTEGER, "teamID" TEXT, "lgID" TEXT, "playerID" TEXT, "salary" INTEGER);
CREATE TABLE "Parks" ("id" SERIAL PRIMARY KEY, "park_key" TEXT, "park_name" TEXT, "park_alias" TEXT, "city" TEXT, "state" TEXT, "country" TEXT);
CREATE TABLE "Schools" ("id" SERIAL PRIMARY KEY, "schoolID" TEXT, "name_full" TEXT, "city" TEXT, "state" TEXT, "country" TEXT);
CREATE TABLE "People" ("id" SERIAL PRIMARY KEY, "playerID" TEXT, "birthYear" TEXT, "birthMonth" TEXT, "birthDay" TEXT, "birthCountry" TEXT, "birthState" TEXT, "birthCity" TEXT, "deathYear" TEXT, "deathMonth" TEXT, "deathDay" TEXT, "deathCountry" TEXT, "deathState" TEXT, "deathCity" TEXT, "nameFirst" TEXT, "nameLast" TEXT, "nameGiven" TEXT, "weight" TEXT, "height" TEXT, "bats" TEXT, "throws" TEXT, "debut" TEXT, "finalGame" TEXT, "retroID" TEXT, "bbrefID" TEXT);
CREATE TABLE "PitchingPost" ("id" SERIAL PRIMARY KEY, "playerID" TEXT, "yearID" INTEGER, "round" TEXT, "teamID" TEXT, "lgID" TEXT, "W" INTEGER, "L" INTEGER, "G" INTEGER, "GS" INTEGER, "CG" INTEGER, "SHO" INTEGER, "SV" INTEGER, "IPouts" INTEGER, "H" INTEGER, "ER" INTEGER, "HR" INTEGER, "BB" INTEGER, "SO" INTEGER, "BAOpp" TEXT, "ERA" TEXT, "IBB" TEXT, "WP" TEXT, "HBP" TEXT, "BK" TEXT, "BFP" TEXT, "GF" INTEGER, "R" INTEGER, "SH" TEXT, "SF" TEXT, "GIDP" TEXT);
CREATE TABLE "Teams" ("id" SERIAL PRIMARY KEY, "yearID" INTEGER, "lgID" TEXT, "teamID" TEXT, "franchID" TEXT, "divID" TEXT, "Rank" INTEGER, "G" INTEGER, "Ghome" TEXT, "W" INTEGER, "L" INTEGER, "DivWin" TEXT, "WCWin" TEXT, "LgWin" TEXT, "WSWin" TEXT, "R" INTEGER, "AB" INTEGER, "H" INTEGER, "_2B" INTEGER, "_3B" INTEGER, "HR" INTEGER, "BB" TEXT, "SO" TEXT, "SB" TEXT, "CS" TEXT, "HBP" TEXT, "SF" TEXT, "RA" INTEGER, "ER" INTEGER, "ERA" DOUBLE, "CG" INTEGER, "SHO" INTEGER, "SV" INTEGER, "IPouts" INTEGER, "HA" INTEGER, "HRA" INTEGER, "BBA" INTEGER, "SOA" INTEGER, "E" INTEGER, "DP" INTEGER, "FP" DOUBLE, "name" TEXT, "park" TEXT, "attendance" TEXT, "BPF" INTEGER, "PPF" INTEGER, "teamIDBR" TEXT, "teamIDlahman45" TEXT, "teamIDretro" TEXT);
CREATE TABLE "Appearances" ("id" SERIAL PRIMARY KEY, "yearID" INTEGER, "teamID" TEXT, "lgID" TEXT, "playerID" TEXT, "G_all" INTEGER, "GS" TEXT, "G_batting" INTEGER, "G_defense" TEXT, "G_p" INTEGER, "G_c" INTEGER, "G_1b" INTEGER, "G_2b" INTEGER, "G_3b" INTEGER, "G_ss" INTEGER, "G_lf" INTEGER, "G_cf" INTEGER, "G_rf" INTEGER, "G_of" INTEGER, "G_dh" TEXT, "G_ph" TEXT, "G_pr" TEXT);
CREATE TABLE "AwardsSharePlayers" ("id" SERIAL PRIMARY KEY, "awardID" TEXT, "yearID" INTEGER, "lgID" TEXT, "playerID" TEXT, "pointsWon" INTEGER, "pointsMax" INTEGER, "votesFirst" TEXT);
CREATE TABLE "TeamsFranchises" ("id" SERIAL PRIMARY KEY, "franchID" TEXT, "franchName" TEXT, "active" TEXT, "NAassoc" TEXT);
CREATE TABLE "Batting" ("id" SERIAL PRIMARY KEY, "playerID" TEXT, "yearID" INTEGER, "stint" INTEGER, "teamID" TEXT, "lgID" TEXT, "G" INTEGER, "AB" INTEGER, "R" INTEGER, "H" INTEGER, "_2B" INTEGER, "_3B" INTEGER, "HR" INTEGER, "RBI" TEXT, "SB" TEXT, "CS" TEXT, "BB" INTEGER, "SO" TEXT, "IBB" TEXT, "HBP" TEXT, "SH" TEXT, "SF" TEXT, "GIDP" TEXT);
CREATE TABLE "ManagersHalf" ("id" SERIAL PRIMARY KEY, "playerID" TEXT, "yearID" INTEGER, "teamID" TEXT, "lgID" TEXT, "inseason" INTEGER, "half" INTEGER, "G" INTEGER, "W" INTEGER, "L" INTEGER, "rank" INTEGER);
CREATE TABLE "FieldingOF" ("id" SERIAL PRIMARY KEY, "playerID" TEXT, "yearID" INTEGER, "stint" INTEGER, "Glf" TEXT, "Gcf" TEXT, "Grf" TEXT);
CREATE TABLE "Pitching" ("id" SERIAL PRIMARY KEY, "playerID" TEXT, "yearID" INTEGER, "stint" INTEGER, "teamID" TEXT, "lgID" TEXT, "W" INTEGER, "L" INTEGER, "G" INTEGER, "GS" INTEGER, "CG" INTEGER, "SHO" INTEGER, "SV" INTEGER, "IPouts" INTEGER, "H" INTEGER, "ER" INTEGER, "HR" INTEGER, "BB" INTEGER, "SO" INTEGER, "BAOpp" TEXT, "ERA" TEXT, "IBB" TEXT, "WP" INTEGER, "HBP" TEXT, "BK" INTEGER, "BFP" TEXT, "GF" INTEGER, "R" INTEGER, "SH" TEXT, "SF" TEXT, "GIDP" TEXT);
CREATE TABLE "CollegePlaying" ("id" SERIAL PRIMARY KEY, "playerID" TEXT, "schoolID" TEXT, "yearID" INTEGER);
CREATE TABLE "HomeGames" ("id" SERIAL PRIMARY KEY, "year_key" INTEGER, "league_key" TEXT, "team_key" TEXT, "park_key" TEXT, "span_first" TEXT, "span_last" TEXT, "games" INTEGER, "openings" INTEGER, "attendance" INTEGER);
CREATE TABLE "HallOfFame" ("id" SERIAL PRIMARY KEY, "playerID" TEXT, "yearid" INTEGER, "votedBy" TEXT, "ballots" TEXT, "needed" TEXT, "votes" TEXT, "inducted" TEXT, "category" TEXT, "needed_note" TEXT);
CREATE TABLE "AwardsShareManagers" ("id" SERIAL PRIMARY KEY, "awardID" TEXT, "yearID" INTEGER, "lgID" TEXT, "playerID" TEXT, "pointsWon" INTEGER, "pointsMax" TEXT, "votesFirst" INTEGER);
CREATE TABLE "BattingPost" ("id" SERIAL PRIMARY KEY, "yearID" INTEGER, "round" TEXT, "playerID" TEXT, "teamID" TEXT, "lgID" TEXT, "G" INTEGER, "AB" INTEGER, "R" INTEGER, "H" INTEGER, "_2B" INTEGER, "_3B" INTEGER, "HR" INTEGER, "RBI" INTEGER, "SB" INTEGER, "CS" TEXT, "BB" INTEGER, "SO" INTEGER, "IBB" INTEGER, "HBP" TEXT, "SH" TEXT, "SF" TEXT, "GIDP" TEXT);
CREATE TABLE "TeamsHalf" ("id" SERIAL PRIMARY KEY, "yearID" INTEGER, "lgID" TEXT, "teamID" TEXT, "Half" INTEGER, "divID" TEXT, "DivWin" TEXT, "Rank" INTEGER, "G" INTEGER, "W" INTEGER, "L" INTEGER);
CREATE TABLE "SeriesPost" ("id" SERIAL PRIMARY KEY, "yearID" INTEGER, "round" TEXT, "teamIDwinner" TEXT, "lgIDwinner" TEXT, "teamIDloser" TEXT, "lgIDloser" TEXT, "wins" INTEGER, "losses" INTEGER, "ties" INTEGER);
CREATE TABLE "FieldingPost" ("id" SERIAL PRIMARY KEY, "playerID" TEXT, "yearID" INTEGER, "teamID" TEXT, "lgID" TEXT, "round" TEXT, "POS" TEXT, "G" INTEGER, "GS" INTEGER, "InnOuts" INTEGER, "PO" INTEGER, "A" INTEGER, "E" INTEGER, "DP" INTEGER, "TP" INTEGER, "PB" TEXT, "SB" TEXT, "CS" TEXT);
CREATE TABLE "AllstarFull" ("id" SERIAL PRIMARY KEY, "playerID" TEXT, "yearID" INTEGER, "gameNum" INTEGER, "gameID" TEXT, "teamID" TEXT, "lgID" TEXT, "GP" TEXT, "startingPos" TEXT);
CREATE TABLE "FieldingOFsplit" ("id" SERIAL PRIMARY KEY, "playerID" TEXT, "yearID" INTEGER, "stint" INTEGER, "teamID" TEXT, "lgID" TEXT, "POS" TEXT, "G" INTEGER, "GS" TEXT, "InnOuts" TEXT, "PO" TEXT, "A" TEXT, "E" TEXT, "DP" TEXT, "PB" TEXT, "WP" TEXT, "SB" TEXT, "CS" TEXT, "ZR" TEXT);
```

**Comment by spacekookie** [comment]
Woops! :speak_no_evil: 
I just published [v0.2.2](https://crates.io/crates/barrel) which should fix the issue, please give it a try

**Comment by spacekookie** [comment]
Oh damn, I forgot that after CI passes this would be closed

**Comment by rippinrobr** [comment]
Thanks for the quick response!  I appreciate that.  I've tried the 0.2.2 version and I'm still getting the id column. I have a question but I'm going to preface it with the fact that I'm pretty new to Rust so I may be wrong but I want to run something by you.  If I'm reading this correctly, it looks like the id column is created before the closure is executed.  https://github.com/spacekookie/barrel/blob/master/src/migration.rs#L99 and since the TableMeta.has_id defaults to true it is writing out the id column even though I said I don't want it.  Like I said, I could be wrong. I updated my code to double check that the TableMeta.has_id was false and it was.  

```
m.create_table(name, move |t| {
   println!("t.meta.has_id: {}", t.meta.has_id);
   for cd in &cols {
      let cname: &str = &cd.name;
      t.add_column(cname, cd.data_type.to_database_type());
   }
   println!("t.meta.has_id: {}", t.meta.has_id);
   println!("t: {:?}", &t.make::<Pg>(true));
}).without_id();
```
Which outputs
```
t.meta.has_id: false
t: ["ADD COLUMN \"id\" SERIAL PRIMARY KEY", "ADD COLUMN \"playerID\" TEXT", "ADD COLUMN \"yearID\" INTEGER", "ADD COLUMN \"stint\" INTEGER", "ADD COLUMN \"teamID\" TEXT", "ADD COLUMN \"lgID\" TEXT", "ADD COLUMN \"POS\" TEXT", "ADD COLUMN \"G\" INTEGER", "ADD COLUMN \"GS\" TEXT", "ADD COLUMN \"InnOuts\" TEXT", "ADD COLUMN \"PO\" TEXT", "ADD COLUMN \"A\" TEXT", "ADD COLUMN \"E\" TEXT", "ADD COLUMN \"DP\" TEXT", "ADD COLUMN \"PB\" TEXT", "ADD COLUMN \"WP\" TEXT", "ADD COLUMN \"SB\" TEXT", "ADD COLUMN \"CS\" TEXT", "ADD COLUMN \"ZR\" TEXT"]
```

**Comment by spacekookie** [comment]
I just released `v0.2.3` which should *definitely* fix your issues :slightly_smiling_face: 

You were right, the code that checked for the existence of certain metadata fields was in the `create_table` function which obviously wouldn't know about any use choices being made.

A side effect of changing the API 20 times before settling on a design :sweat_smile:

**Comment by rippinrobr** [comment]
I can totally relate to that!  Thank you. I will update my version this evening and test it out.  Again, thank you for the quick responses. I do appreciate it.

**Comment by rippinrobr** [comment]
tried v0.2.3 and received the following:

```
▶ cargo build
   Compiling csv2api v0.1.0 (file:///Users/robertrowe/src/csv2api)
error[E0432]: unresolved import `barrel::backend::Pg`
 --> src/workers/sql_gen.rs:5:5
  |
5 | use barrel::backend::Pg;
  |     ^^^^^^^^^^^^^^^^^^^ no `Pg` in `backend`
```

Here are my `use` statements:

```
use std::fs::File;
use std::io::Error;
use std::io::prelude::*;
use barrel::*;
use barrel::backend::Pg;
use models::ColumnDef;
```
I've also included the source file  too just in case.

[sql_gen.txt](https://github.com/spacekookie/barrel/files/2112555/sql_gen.txt)

**Comment by spacekookie** [comment]
That is *really* weird. Can you please show me your `Cargo.toml` file? Because the examples (using the same imports) work for `v0.2.3` :thinking:

**Comment by rippinrobr** [comment]
Yes! I can compile and generate the SQL without the id field! Thank you for the fix! :)

**Comment by spacekookie** [comment]
I'll close this then :slightly_smiling_face: Thanks for reporting the issue!
